# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 07:54
from __future__ import unicode_literals

import coffeehouse.jj2app.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jj2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='store',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='date_lastupdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='timestamp_lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default=coffeehouse.jj2app.models.default_city, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
