# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj2app', '0003_auto_20180324_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='field_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='field_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
