# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 14:23
from __future__ import unicode_literals

import coffeehouse.jj2app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj2app', '0005_item_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.IntegerField(null=True, validators=[coffeehouse.jj2app.models.calorie_watcher]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(help_text='Ensure you provide some desc', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ITEM NAME'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
