# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeehouseuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='coffeehouseuser',
            table='member',
        ),
    ]
